apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: integration-suite-test-application-oazh
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: integration-suite-test-component-git-source-lrpc
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: integration-suite-test-component-git-source-lrpc
  namespace: appstudio-e2e-test
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: integration-suite-test-component-git-source-lrpc
status:
  configuration:
    generatedName: ""
